//const mongoose = require("mongoose");
const requireLogin = require("../middlewares/requireLogin");
const Boards = require("../models/Boards");

//const Boards = mongoose.model("Board");
//Get all public boards
module.exports = app => {
  app.get("/api/boards", requireLogin, (req, res) => {
    Boards.find(
      {
        privacy: false
      },
      (err, result) => {
        if (err) {
          res.send(err);
        }
        res.json(result);
      }
    );
    console.log(req.body);
    const { title, name, description, image, creator } = req.body;

    //creating instance of Boards
    const boards = new Boards({
      title,
      name,
      description,
      image,
      _creator: req.user.id, //automatically generated by mongoose
      createdAt: Date.now(),
      url
    });
  });
};
